repos:
    - repo: https://github.com/timothycrosley/isort
      rev: 5.9.1
      hooks:
          - id: isort
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.910
      hooks:
          - id: mypy
    - repo: https://github.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
default_language_version:
    python: python3
