repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        language_version: python3.9
      - id: end-of-file-fixer
        language_version: python3.9
      - id: check-builtin-literals
        language_version: python3.9
      - id: check-merge-conflict
        language_version: python3.9
      - id: debug-statements
        language_version: python3.9
      - id: check-added-large-files
        language_version: python3.9
      - id: check-ast
        language_version: python3.9
      - id: check-json
        language_version: python3.9
      - id: check-symlinks
        language_version: python3.9
      - id: check-yaml
        language_version: python3.9
      - id: double-quote-string-fixer
        language_version: python3.9
      # Using the args --django, it tests the test_*.py pattern
      # Check the README https://github.com/pre-commit/pre-commit-hooks#name-tests-test
      - id: name-tests-test
        name: Tests should start in _test.py
        language_version: python3.9
        args: ['--django']
  - repo: 'https://github.com/pycqa/flake8'
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        types:
          - python
        language_version: python3.9
